defaults_pg: &defaults_pg
  adapter: postgresql
  port: 5432
  encoding: unicode
  database:
  pool: 5
  username: k
  password: k

development:
  <<: *defaults_pg
  database: pullq_dev

test:
  <<: *defaults_pg
  database: pullq_test

production:
  <<: *defaults_pg
  database: pullq_prod